// <auto-generated />
namespace MessageLog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LogModelUseType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogModelUseType));
        
        string IMigrationMetadata.Id
        {
            get { return "201804300835475_Log-Model-UseType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
