// <auto-generated />
namespace MessageLog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LogModelMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogModelMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201804300941076_Log-Model-Message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
