// <auto-generated />
namespace Contracts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ContractNamesFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContractNamesFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201326249_Contract-Names-Fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
