// <auto-generated />
namespace PublicService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AccountsWithoutDevs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountsWithoutDevs));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131037526_Accounts-Without-Devs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
