version: '3'

services:
  proxy:
    ports:
      - "3000"

  centralserver:
    environment:
      - ContractContext= <InsertYourConnectionStringHere>
    ports:
      - "3001"

  adsmock:
    ports:
      - "3002"
  
  messagelog:
    environment:
      - LogContext= <InsertYourConnectionStringHere>
      - Hostname=<...>
      - Port=<...>
      - Username=<...>
      - Password=<...>
      - ChainName=<...>
      - BurnAddress=<...>
      - RootNodeAddress=<...>
    ports:
      - "3003"

  web:
    environment:
      - PSContext= <InsertYourConnectionStringHere>
    ports:
      - "3004"

