version: '3'

services:
  proxy:
    ports:
      - "80"
  centralserver:
    environment:
      - ContractContext=Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\ContractContext.mdf;Integrated Security=True;
    ports:
      - "80"
  adsmock:
    ports:
      - "80"
networks:
  default:
    external:
      name: nat


