version: '3'

services:
  proxy:
    container_name: proxy
    image: proxy
    build:
      context: .\Proxy
      dockerfile: Dockerfile
    networks:
      - beroad
    depends_on:
      - centralserver
      - adsmock

  centralserver:
    container_name: centralserver
    image: centralserver
    build:
      context: .\CentralServer
      dockerfile: Dockerfile
    networks:
      - beroad
    depends_on:
      - sqlserver
      
  sqlserver:
    image: microsoft/mssql-server-windows-express
    container_name: sqlserver
    environment:
      sa_password: ""
      ACCEPT_EULA: Y
    networks:
      - beroad

  adsmock:
    container_name: adsmock
    image: adsmock
    build:
      context: .\ADSMock
      dockerfile: Dockerfile
    networks:
      - beroad

networks:
  default:
    external:
      name: nat
  beroad:
  

