version: '3'

services:
  sqlserver:
    image: microsoft/mssql-server-windows-express
    container_name: sqlserver
    environment:
      sa_password: ""
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  proxy:
    ports:
      - "80"

  centralserver:
    environment:
      - ContractContext="Server=sqlserver;Database=ContractContext.mdf"
    ports:
      - "80"

  adsmock:
    ports:
      - "80"
networks:
  default:
    external:
      name: nat


