version: '3'

services:
  proxy:
    container_name: proxy
    image: proxy
    build:
      context: .\Proxy
      dockerfile: Dockerfile
    networks:
      - beroad
    depends_on:
      - adsmock
      - centralserver

  centralserver:
    container_name: centralserver
    image: centralserver
    build:
      context: .\CentralServer
      dockerfile: Dockerfile
    networks:
      - beroad

  adsmock:
    container_name: adsmock
    image: adsmock
    build:
      context: .\ADSMock
      dockerfile: Dockerfile
    networks:
      - beroad


